import type { Metadata } from "next";
import "./globals.css";
import { ScrollToTopButton } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Novel Insights - Books reviews website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
